[package]
name = "ppot-verifier"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "verify_ppot"

[[bin]]
name = "downloader"

[dependencies]
# ark-groth16 = { version = "0.3.0", default-features = false }
# ark-poly = { version = "0.3.0", default-features = false }
# ark-relations = { version = "0.3.0", default-features = false }
ark-bn254 = { version = "0.3.0", default-features = false, features = ["curve", "scalar_field"] }
ark-ec = { version = "0.3.0", default-features = false}
ark-ff = { version = "0.3.0", default-features = false}
ark-serialize = { version = "0.3.0", default-features = false, features = ["derive", "std"] }
ark-std = { version = "0.3.0", default-features = false }
blake2 = { version = "0.10.4", default-features = false }
curl = "0.4.44"
# byteorder = { version = "1.4.3", default-features = false }
derivative = { version = "2.2.0", default-features = false, features = ["use_core"] }
# manta-crypto = { path = "../manta-crypto", default-features = false, features = ["arkworks", "getrandom"] }
# manta-util = { path = "../manta-util", default-features = false }
memmap = "0.7.0"
# rand_chacha = { version = "0.3.1", default-features = false }

[dev-dependencies]
ark-r1cs-std = { version = "0.3.1", default-features = false }
ark-snark = { version = "0.3.0", default-features = false }
# manta-accounting = { path = "../manta-accounting", default-features = false }
# manta-parameters = { path = "../manta-parameters", default-features = false, features = ["download"] }
# manta-pay = { path = "../manta-pay", default-features = false, features = ["groth16", "test"] }
# manta-trusted-setup = { path = ".", default-features = false, features = ["test"] }
# memmap = "0.7.0"
# tempfile = { version = "3.3.0", default-features = false }
